### ISSUE TITLE
5.0.0 bump question

### ISSUE THREAD

**Issue by Fritzybois** [jfrog/artifactory-gradle-plugin#35]
### How can we help?

Hi, im trying to bump to the newest version but I cant seem to figure out how to deal with the resolve part.

This is how it used to look in 4.32.0
```
artifactory {
    contextUrl = "${project.properties['artifactory_contextUrl'] ?: System.env.ARTIFACTORY_URL}"
    resolve {
        repository {
            repoKey = version.endsWith('SNAPSHOT') ? 'snapshot-standard' : 'release-standard'
            username = "${project.properties['artifactory_user'] ?: System.env.ARTIFACTORY_USER}"
            password = "${project.properties['artifactory_password'] ?: System.env.ARTIFACTORY_PASSWORD}"
            maven = true
        }
    }
}
```

I cant figure out how resolve is supposed to be handled in the new version

**Comment by attiasas** [comment]
Hi @Fritzybois, thank you for opening this issue. the 'resolve' attribute removed. 
You can follow this [documentation](https://docs.gradle.org/current/userguide/declaring_repositories.html#declaring-repositories) for different ways to configure your repositories with Gradle, check out our [gradle project examples](https://github.com/JFrog/project-examples/tree/master/gradle-examples?_gl=1*pgsvlz*_ga*MTc3OTI0ODE4NS4xNjYyMjgxMjI1*_ga_SQ1NR9VTFJ*MTY4NTM2OTcwMC4yNi4wLjE2ODUzNjk3MDAuNjAuMC4w) or you can use this Kotlin snippet and adjust it

```kotlin
repositories { 
    maven {
        // The Artifactory (preferably virtual) repository to resolve from 
        url = uri("http://repo.myorg.com/artifactory/libs-releases")
        // Optional resolver credentials (leave out to use anonymous resolution)
        credentials {
            // Artifactory's username
            username = "resolver"
            // Password or API Key
            password = "resolverPaS*" 
        } 
    }
  }
```

**Comment by Fritzybois** [comment]
Thanks, think we managed to figure it out by using what you suggested.
