### ISSUE TITLE
How does the plugin get configuration information from the JFrog CLI?

### ISSUE THREAD

**Issue by prestontim** [jfrog/artifactory-gradle-plugin#47]
### How can we help?

I have a question about the JFrog CLI in respect to how it's integrated with Gradle. When I'm executing a GitHub Action, I am running the steps shown here: 

![image](https://github.com/jfrog/artifactory-gradle-plugin/assets/8949320/83d18e82-da18-4823-b41c-2aec3a4dd01d)

My question: When I'm executing the "jf gradle" command, do I have access inside Gradle (in an extension or something) to what is set via the "--repo-deploy" switch passed to the "jf gradle-config" command? I'm trying to get access to this information for an in-house plugin that I'm currently working on.

I've launched both the JFrog CLI and Gradle with debug logging and nothing is really jumping out at me.

Thanks for your time!

**Comment by yahavi** [comment]
@prestontim,
When you use `jf gradle`, the JFrog CLI injects the Gradle Artifactory plugin using a Gradle [init script](https://github.com/jfrog/build-info/blob/build-info-gradle-extractor-4.33.4/build-info-extractor-gradle/src/main/resources/initscripttemplate.gradle). This plugin is responsible for gathering the publication and extracting deployment candidates. Eventually, the complete artifacts and build-info are sent for publication to Artifactory.

If you could provide more details about your goal, I could offer you a more precise answer.

**Comment by yahavi** [comment]
@prestontim
Appreciate you sharing the use case. I'm a bit uncertain about whether you're aiming to configure the repository key for the Gradle Artifactory plugin or if your goal is to retrieve the repository key.

From the provided screenshot, it appears that you're attempting to establish the deployment repository, distinguishing between snapshot and release. The plugin's code already handles the decision-making process for deploying to either repository, depending on the deployment path. For instance, if the path contains "-SNAPSHOT," the deployment is directed to the snapshot repository. You can check the implementation here: [PublicationUtils.java#L406](https://github.com/jfrog/artifactory-gradle-plugin/blob/5.1.2/src/main/java/org/jfrog/gradle/plugin/artifactory/utils/PublicationUtils.java#L406).

That being said, there's still a bit of fine-tuning needed before we can roll out this feature completely. You can take a look at the necessary adjustments here: https://github.com/yahavi/artifactory-gradle-plugin/commit/2bb42350daa11001a4adab2e89dea0d41ddd5374.

Example:
```groovy
publish {
  repository {
    releaseRepoKey = 'libs-release-local'
    snapshotRepoKey = 'libs-snapshot-local'
  }
}
```

If we were to implement this feature, would it fulfill your requirements? 
Thanks!

**Comment by yahavi** [comment]
@prestontim 
In Gradle Artifactory plugin v5.2.0 we added the above functionality of configuring release and snapshot repositories.
Feel free to use it and share your feedback with us.
